# Variables that contain the user credentials to access the Twitter API.
ACCESS_TOKEN = "ENTER_YOUR_ACCESS_TOKEN"
ACCESS_TOKEN_SECRET = "ENTER_YOUR_ACCESS_TOKEN_SECRET"
CONSUMER_KEY = "ENTER_YOUR_CONSUMER_KEY"
CONSUMER_SECRET = "ENTER_YOUR_CONSUMER_SECRET"
